### PR TITLE
Adds conic gradients

### LINKED ISSUE #16: Conical Gradients
**Is your feature request related to a problem? Please describe.**
Make [conical gradients](https://leaverou.github.io/conic-gradient/) an option like radial and linear gradients.

**Describe the solution you'd like**
Use the polyfill

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by SaraVieira**
## Type of Change

- [ ] Bugfix (a fix that does not break existing functionality)
- [x] Enhancement (new feature/minor improvement)
- [ ] Breaking change (fix or feature that would cause existing functionality to break)

## What is Changed

Adds Conic gradients

## Comments
YAY

screenshot 2018-12-06 at 17 46 58
screenshot 2018-12-06 at 17 47 07

## Checklist

- [x] I have read the **CONTRIBUTING** guideline.
- [x] I have given this pull request a clear and descriptive title
- [x] I have clearly described the changes that this pull request makes
- [x] I have included relevant information or comments

closes #16

### CODE REVIEW

**Comment by SaraVieira** [comment]
screenshot 2018-12-06 at 17 49 44


Also accepts comments

**Comment by vicbergquist** [comment]
girl you're on fire tonight! 😍 thank uuu

**Comment by vicbergquist** [comment]
they're not working for me 😢

**Comment by SaraVieira** [comment]
@vicbergquist 

I didn't see that in the polyfill docs.

Is this what you mean

```css
/* Starburst with repeating gradients */
background: #0ac
repeating-conic-gradient(hsla(0,0%,100%,.2) 0 15deg, hsla(0,0%,100%,0) 0 30deg);
```

**Comment by vicbergquist** [comment]
@SaraVieira 

No, I mean the same as how it works with the normal gradients (repeat vs. no-repeat) Like this, so that you can choose between the gradient being repeated or not inside its box. 
screenshot 2018-12-07 09 25 35
screenshot 2018-12-07 09 24 53

**Pull request merged**
