### PR TITLE
Check that input field percentages are not >100%

### PR DESCRIPTION
**Pull request by MichaelE1**
## Type of Change

- [x] Bugfix (a fix that does not break existing functionality)
- [ ] Enhancement (new feature/minor improvement)
- [ ] Breaking change (fix or feature that would cause existing functionality to break)

## What is Changed

Currently it is possible to input a percentage greater than 100 on canvas size, color stops and box details input fields. This PR introduces a method to check that the percentage is not greater than 100.
## Comments

:)

## Checklist

- [x] I have read the **CONTRIBUTING** guideline.
- [x] I have given this pull request a clear and descriptive title
- [x] I have clearly described the changes that this pull request makes
- [x] I have included relevant information or comments

### CODE REVIEW

**Comment by vicbergquist** [comment]
This is great, thank you Micheal!
But what about the x axis and y axis inputs, where the input can be above 100% to place something off the canvas.. I'm currently working on some new max/min value calculations that can be combines with this. So instead of it always checking it against 100, it will check it against the max/min value passed down. What do you think?

**Comment by MichaelE1** [comment]
That sounds great Victoria. Now that I'm looking at this for a second time, I'm unsure if it's even a good approach. It's valid to have CSS percentages greater than 100, but there's understandably a limitation to what you can preview in Shapy. 

You keep going ahead with the new max/min calculations. Feel free to not merge this if it makes life easier 😅

**Comment by vicbergquist** [comment]
I think it makes sense to have this, so that it won't go over the max values. It's just that the max values are all wrong now.. This is great for the max values for the canvas, box and color stop sizes I think, but for the X and Y axis placements, the max would be the when the box/shape is completely outside the box/canvas, if that makes sense... What do you think?

**Comment by MichaelE1** [comment]
@vicbergquist Yes, that makes sense. Sounds good to me!

**Comment by vicbergquist** [comment]
I think I fixed this? 😅

**Comment by MichaelE1** [comment]
@vicbergquist Yeah, I just a quick go and it seems better. Nicely done 💯

**Pull request closed without merging**
