### PR TITLE
Add url & screenshot to readme

### PR DESCRIPTION
**Pull request by MichaelE1**

### CODE REVIEW

**Comment by vicbergquist** [comment]
Thank you!

**Comment by vicbergquist** [comment]
The screenshot should probably be in a root folder in the repo. Could you add the img in a docs/assets folder, please? 😃

**Comment by MichaelE1** [comment]
Sure can. While I'm at it, are we moving the README into the docs folder too? Sorry for basing on master btw. Didn't realise you had a dev branch 😬

**Comment by vicbergquist** [comment]
> Sure can. While I'm at it, are we moving the README into the docs folder too? Sorry for basing on master btw - didn't realise you had a dev branch 😬

No, the readme can be on the root!
And no worries, I just created it! Didn't realise it was missing 😅 It's just been me working on it, so I'd like to start adding PR and issue templates etc. ASAP and documentation as well.

**Pull request merged**
